import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from 'next/font/google';
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";
import ClientOnly from "./components/ClientOnly";
import dynamic from 'next/dynamic';
import SessionExpiredModal from "./components/Modals/SessionExpiredModal";

// Optimize font loading
const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  preload: true,
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['400', '500', '600'], // Only load needed weights
});

// Lazy load modals
const ToasterProvider = dynamic(() => import("./providers/ToasterProviders"), { ssr: false });
const RegisterModal = dynamic(() => import("./components/Modals/RegisterModal"), { ssr: false });
const LoginModal = dynamic(() => import("./components/Modals/LoginModal"), { ssr: false });
const ConfirmModal = dynamic(() => import("./components/Modals/ConfirmModal"), { ssr: false });

export const metadata: Metadata = {
  title: "RentEase",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    // Optional: Add different sizes for better device support
    apple: [
      { url: '/favicon.ico' },
      { url: '/icon.png', sizes: '192x192', type: 'image/png' },
    ],
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  
  return (
    <html lang="en" className="overflow-y-auto">
      <body className={`${inter.className} ${poppins.variable} overflow-y-auto`}>
        <div className="min-h-screen overflow-y-auto">
          <ClientOnly>
            <ToasterProvider />
            <RegisterModal />
            <LoginModal />
            <ConfirmModal />
            <SessionExpiredModal />
          </ClientOnly>
          <main className="overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
